/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class", // Enable class-based dark mode
  // content: [],
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'absa-passion': '#DC0037',
        'absa-power': '#B50232',
        'absa-hope': '#95052A',
        'absa-inspire': '#77021E',
        'absa-energy': '#FF780F',
        'absa-uplift': '#F93F24',
        'absa-enrich': '#131010',
        'absa-serene': '#FFFFFF',
        primary: '#a40022',
        'on-primary': '#ffffff',
        'primary-container': '#ffd9dd',
        'on-primary-container': '#410007',
        'primary-fixed': '#ffdad8',
        'on-primary-fixed': '#410007',
        'on-primary-fixed-variant': '#92001d',
        'inverse-primary': '#ffb3b8',
        'primary-fixed-dim': '#ffb3b8',
        secondary: '#5d3f3e',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd9d9',
        'on-secondary-container': '#636262',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#e6bdbd',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        tertiary: '#775653',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#67686a',
        'on-tertiary-container': '#e8e8ea',
        'tertiary-fixed': '#e2e2e4',
        'tertiary-fixed-dim': '#c6c6c8',
        'on-tertiary-fixed': '#1a1c1d',
        'on-tertiary-fixed-variant': '#454749',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fffbff',
        'on-background': '#201a1a',
        surface: '#fffbff',
        'on-surface': '#201a1a',
        'on-surface-variant': '#5d3f3e',
        'surface-variant': '#e4e2e2',
        'inverse-surface': '#362f2f',
        'inverse-on-surface': '#fbeeec',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2f1',
        'surface-container': '#f5ecfc',
        'surface-container-high': '#efe6e5',
        'surface-container-highest': '#e9e0e0',
        'surface-dim': '#dbdad9',
        'surface-bright': '#ffffff',
        'surface-tint': '#bf0029',
        outline: '#857371',
        'outline-variant': '#d8c2c0',
        // Existing color tokens
        'background-soft': 'var(--color-background-soft)',
        'background-muted': 'var(--color-background-muted)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
        },
        brand: {
          primary: 'var(--brand-primary)',
          'primary-hover': 'var(--brand-primary-hover)',
          secondary: 'var(--brand-secondary)',
          'secondary-hover': 'var(--brand-secondary-hover)',
          soft: 'var(--brand-soft)',
          'soft-success': 'var(--brand-soft-success)',
        },
        status: {
          info: 'var(--color-info)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
        },
      },
      fontFamily: {
        sans: ['"Hanken Grotesk"', 'var(--font-family-main)', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['var(--font-family-main)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'label-caps': ['"Hanken Grotesk"', 'sans-serif'],
        'metric-lg': ['"Hanken Grotesk"', 'sans-serif'],
        headline: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        label: ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'label-sm': ['12px', { lineHeight: '16px' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'metric-lg': ['36px', { lineHeight: '44px', fontWeight: '700' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        gutter: '24px',
        'card-padding': '24px',
        panel: '1.5rem',
        'panel-sm': '1rem',
        touch: '2.75rem',
        grid: 'var(--space-grid)',
        'space-1': 'var(--space-1)',
        'space-2': 'var(--space-2)',
        'space-3': 'var(--space-3)',
        'space-4': 'var(--space-4)',
        'space-6': 'var(--space-6)',
        'space-8': 'var(--space-8)',
        'space-10': 'var(--space-10)',
        'space-12': 'var(--space-12)',
        'space-16': 'var(--space-16)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        card: 'var(--radius-card)',
        button: 'var(--radius-button)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        ub: 'var(--shadow-sm)',
        'ub-md': 'var(--shadow-md)',
        'ub-lg': 'var(--shadow-lg)',
      },
      zIndex: {
        shell: '10',
        header: '30',
        backdrop: '40',
        popover: '50',
        modal: '60',
        toast: '70',
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 3s infinite',
        fadeIn: 'fadeIn 1s ease-in forwards',
        'loading-bar': 'loading-bar 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '50%': { transform: 'translate(20px, -20px)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'loading-bar': {
          '0%': { transform: 'translateX(-100%)' },
          '50%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
