
import { ref, computed } from 'vue';
import { decodeJWT } from '@/services/decodeJWT';
import API_BASE_URL from '@/services/api';
import { getUsers, createUser, updateUser, deleteUser } from '@/api_services/owners_api.js';
import { availableModules } from '@/config/moduleCards.js';

// Global state (if we want to share across components, define outside function)
// For now, we'll keep it scoped to the composable instance or use a shared state pattern if requested "fully implement state management". 
// Usually for a management module, fresh data on mount is fine, but keeping it reactive is good.
// I will keep state local to the composable function for now to avoid side effects if reused, 
// unless the user specifically implies global store behavior. 
// "Fully implement state management" often implies moving logic out of .vue.

export function useUserManagement() {

    // --- State ---
    const users = ref([]);
    const branches = ref([]);
    const subscribedModules = ref([]);

    const loading = ref({
        users: false,
        branches: false,
        modules: false,
        action: false // for create/update/delete operations
    });

    const error = ref(null);
    const successMessage = ref('');

    // --- Computed ---
    const filteredModules = computed(() => {
        return availableModules.map(module => ({
            ...module,
            available: !module.requiresSubscription || subscribedModules.value.some(m => m.id === module.id)
        }));
    });

    // --- Actions ---

    const clearMessages = () => {
        error.value = null;
        successMessage.value = '';
    };

    const setSuccess = (msg) => {
        successMessage.value = msg;
        setTimeout(() => {
            successMessage.value = '';
        }, 3000);
    };

    const setError = (err) => {
        console.error(err);
        error.value = err.message || 'An error occurred';
        setTimeout(() => {
            error.value = null;
        }, 5000);
    };

    // 1. Users Management
    const fetchUsers = async () => {
        loading.value.users = true;
        try {
            const data = await getUsers();
            users.value = Array.isArray(data) ? data : [];
        } catch (err) {
            setError(err);
        } finally {
            loading.value.users = false;
        }
    };

    const addUser = async (userData) => {
        loading.value.action = true;
        clearMessages();
        try {
            const payload = {
                ...userData
            };

            const res = await fetch(`${API_BASE_URL}/users/add`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const errData = await res.json().catch(() => ({}));
                throw new Error(errData.detail || 'Failed to add user');
            }

            // On success, refresh list or push to local
            // users.value.push({ ...userData }); // pushing might miss ID generated by backend
            await fetchUsers();
            setSuccess('User added successfully');
            return true;
        } catch (err) {
            setError(err);
            return false;
        } finally {
            loading.value.action = false;
        }
    };

    const editUser = async (userData) => {
        loading.value.action = true;
        clearMessages();

        try {
            const payload = {
                ...userData
            };

            const res = await fetch(`${API_BASE_URL}/users/update`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const err = await res.json();
                throw new Error(err.detail || 'Failed to update user');
            }

            await fetchUsers();
            setSuccess('User updated successfully');
            return true;
        } catch (err) {
            setError(err);
            return false;
        } finally {
            loading.value.action = false;
        }
    };

    const removeUser = async (email) => {
        loading.value.action = true;
        clearMessages();
        try {
            const res = await fetch(`${API_BASE_URL}/users/remove?email=${encodeURIComponent(email)}`, {
                method: 'DELETE'
            });

            if (res.ok) {
                // users.value = users.value.filter(u => u.email !== email);
                await fetchUsers();
                setSuccess('User removed successfully');
                return true;
            } else {
                const errorData = await res.json().catch(() => ({}));
                throw new Error(errorData.detail || 'Failed to remove user');
            }
        } catch (err) {
            setError(err);
            return false;
        } finally {
            loading.value.action = false;
        }
    };

    // 2. Branches Management
    const fetchBranches = async () => {
        loading.value.branches = true;
        try {
            const res = await fetch(`${API_BASE_URL}/subaccounts/branches/list`);
            if (res.ok) {
                const data = await res.json();
                branches.value = Array.isArray(data) ? data : [];
            }
        } catch (e) {
            console.warn('Failed to fetch branches', e);
            // Don't set main error for branches failure, just warn?
        } finally {
            loading.value.branches = false;
        }
    };

    const addBranch = async (branchData) => {
        loading.value.action = true;
        clearMessages();
        try {
            const payload = {
                ...branchData
            };

            const res = await fetch(`${API_BASE_URL}/subaccounts/branches`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const err = await res.json().catch(() => ({}));
                throw new Error(err.detail || 'Failed to create branch');
            }

            await fetchBranches();
            setSuccess('Branch created successfully');
            return true;
        } catch (e) {
            setError(e);
            return false;
        } finally {
            loading.value.action = false;
        }
    };

    const removeBranch = async (branchId) => {
        loading.value.action = true;
        clearMessages();
        try {
            const res = await fetch(`${API_BASE_URL}/subaccounts/branches/${branchId}`, {
                method: 'DELETE'
            });
            if (!res.ok) throw new Error('Failed to delete branch');

            await fetchBranches();
            setSuccess('Branch deleted successfully');
            return true;
        } catch (e) {
            setError(e);
            return false;
        } finally {
            loading.value.action = false;
        }
    };

    // 3. Modules
    const fetchSubscribedModules = async () => {
        const tenantId = getTenantId();
        loading.value.modules = true;
        try {
            const res = await fetch(`${API_BASE_URL}/modules-manager/owner/modules?tenant_id=${tenantId}`);
            const data = await res.json();
            const subscribedModuleIds = data.modules || [];

            subscribedModules.value = availableModules.filter(module =>
                !module.requiresSubscription || subscribedModuleIds.includes(module.id)
            );
        } catch (err) {
            console.error('Error fetching modules:', err);
            subscribedModules.value = availableModules.filter(module => !module.requiresSubscription);
        } finally {
            loading.value.modules = false;
        }
    };

    // Helpers
    const getBranchName = (branchId) => {
        const branch = branches.value.find(b => b._id === branchId || b.id === branchId);
        return branch ? branch.name : 'Unknown Branch';
    };

    const isModuleAvailable = (moduleId) => {
        const module = availableModules.find(m => m.id === moduleId);
        return !module || !module.requiresSubscription || subscribedModules.value.some(m => m.id === moduleId);
    };

    const getModuleTitle = (moduleId) => {
        return availableModules.find(m => m.id === moduleId)?.title || moduleId;
    };

    return {
        // State
        users,
        branches,
        subscribedModules,
        filteredModules,
        loading,
        error,
        successMessage,

        // Actions
        fetchUsers,
        addUser,
        editUser,
        removeUser,
        fetchBranches,
        addBranch,
        removeBranch,
        fetchSubscribedModules,

        // Helpers
        clearMessages,
        getBranchName,
        isModuleAvailable,
        getModuleTitle
    };
}
